{% set name = "llnl-sina" %}
{% set version = "1.14.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/Sina/archive/v{{ version }}.tar.gz
  sha256: ccf366cb7aff365510503ca4e46685ba96524e77dfa74a91c5b981c25aa2e749 

build:
  number: 1
  noarch: python
  script:
    - cd python
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sina = sina.cli.driver:main


requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six
    - sqlalchemy <2
    - orjson

test:
  imports:
    - sina
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LLNL/Sina
  summary: A tool for storing Sina-format data to one or more backends (SQL, Cassandra) and querying it using a unified, beginner-friendly Python API.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HaluskaR
    - doutriaux1
